### ISSUE TITLE
File test_TCPIPSocketServerEcho.cpp should go into thirdParty folder

### ISSUE THREAD

**Issue by bernhard-thiele** [modelica-3rdparty/Modelica_DeviceDrivers#110]
The file 

Modelica_DeviceDrivers/Modelica_DeviceDrivers/Resources/test/Communication/test_TCPIPSocketServerEcho.cpp 

states that is from https://msdn.microsoft.com/en-us/library/windows/desktop/ms737593.aspx

Hence, it should be below thirdParty, shouldn't it?

**Comment by tbeu** [comment]
Do not think so. Well, 
- it has undefined license
- and there is no thirdParty folder in the test folder.

**Comment by bernhard-thiele** [comment]
Undefined license doesn't mean that it is in the public domain. We can have another directory under thirdParty for it. Legally, that is the cleaner solution. The build/test scripts can be adapted to it. Actually, if it has no license and we don't know if it is considered to be in the public domain we need to think whether we remove it entirely. 

This licensing aspect is very important for tool vendors that ship this library. We cannot take  that lightly.

**Comment by tbeu** [comment]
http://stackoverflow.com/questions/2181578/licensing-for-msdn-code-samples

**Comment by bernhard-thiele** [comment]
Okay, when we have " Microsoft Limited Public License" for this code. As I understand it this makes it fine to include it under thirdParty together with a copy of the license since it states

```
If you distribute any portion of the software in source code form, you may do so only under this license by including a complete copy of this license with your distribution
```

**Comment by tbeu** [comment]
New folder thirdParty in folder test or existing folder thirdParty?

**Comment by bernhard-thiele** [comment]
The existing folder thirdParty. The idea is to collect all third party code there, so that it is separated from the rest and particularly vendors have an easy overview about it when checking licenses on whether they can ship it safely.

**Comment by tbeu** [comment]
OK, then put it in thirdParty\Microsoft

**Comment by bernhard-thiele** [comment]
Good, that fits well

**Comment by bernhard-thiele** [comment]
Missed that this was is not yet resolved and just did the release. This should be resolved, but probably not so severe that we immediately need a 1.4.5 release
