### ISSUE TITLE
Modelica compatibility of SerialPackager (and alternative packagers)

### ISSUE THREAD

**Issue by bernhard-thiele** [modelica-3rdparty/Modelica_DeviceDrivers#112]
The SerialPackager is know to be difficult to support on different tools. This ticket shall collect some issues and serve for discussions including support for additional alternative packagers.

It is not planned to remove the SerialPackager nor change it in a non-backwards-compatible way. 

Some issues on Modelica incompatibility have been reported in ticket #107 as well as ideas on which a new packager could be built.

**Comment by tbeu** [comment]
It is not about SimulationX. It is about Modelica-compatibility.

**Comment by bernhard-thiele** [comment]
Closing this for being non-active.
