### ISSUE TITLE
Consistent naming of struct variables

### ISSUE THREAD

**Issue by tbeu** [modelica-3rdparty/Modelica_DeviceDrivers#150]
The struct members between the Win and Linux C implementation often have different names where they mean the same thing actually. This could be improved to have a consistent variable naming within a specific driver (and even throught the whole library).

**Comment by bernhard-thiele** [comment]
Sometimes also the implementations are quite a bit different. Don't think that it is a big issue if variable names differ a bit. I don't mind If you want to change the Windows part to be closer to the Linux, but I don't think it is very worthwhile and I would rather avoid to enter a time consuming discussion about how to (re)name variables. Maybe worth to have a bit of an eye on it in new developments, but I currently wouldn't dig into it for the existing code.
