### ISSUE TITLE
Event triggered message print block for debugging

### ISSUE THREAD

**Issue by bernhard-thiele** [modelica-3rdparty/Modelica_DeviceDrivers#289]
Add an utility block for debugging purposes which prints a message when triggered by an event.

**Comment by beutlich** [comment]
If implemented by `when` statements it is very likely that the message is printed more than once. Anyway ...

**Comment by bernhard-thiele** [comment]
It should be only printed once at an event instant. It is more a debugging related block, so I don't think it's worth to have a dedicated example for it.
