### ISSUE TITLE
Failed check for SBHS

### ISSUE THREAD

**Issue by HansOlsson** [modelica-3rdparty/Modelica_DeviceDrivers#316]
Check of Modelica_DeviceDrivers.EmbeddedTargets.AVR.Examples.SBHS.Board fails in Dymola.

There are two issues:

- The units for input/output on gain1 are swapped!
-  lastRefreshTemp and lastRefresh are declared as discrete Real, but given a value in a when-clause

**Comment by bernhard-thiele** [comment]
@sjoelund  I will try to fix it, unless you would like to do it.

**Comment by bernhard-thiele** [comment]
#318 fixes the two described issues.
