### ISSUE TITLE
Examples in M_DD make use of deprecated block SynchronizeRealtime

### ISSUE THREAD

**Issue by dietmarw** [modelica-3rdparty/Modelica_DeviceDrivers#354]
I noticed that the majority of the examples in the library still uses `SynchronizeRealtime` when that class itself says: "Deprecated block. Use "RealtimeSynchronize" instead." 

I can understand to keep `SynchronizeRealtime` around for backward in order to not break user-models but the examples within the library should really follow its own instruction and use the new `RealtimeSynchronize` (also in order to educate new users).

**Comment by bernhard-thiele** [comment]
Yes, you are of course right. Fixed it.
