### ISSUE TITLE
ModelicaUtilities.c includes ModelicaUtilities.h in wrong directory

### ISSUE THREAD

**Issue by TilmanBuente** [modelica-3rdparty/Modelica_DeviceDrivers#367]
Resources/test/Util/ModelicaUtilities.c:

please replace line 1
#include "ModelicaUtilities.h"
by
#include "../../Include/ModelicaUtilities.h"

**Comment by tbeu** [comment]
Actually, ModelicaUtilities.h is tool-specific (and as such provided by the Modelica environement). Hence, the include statement is correct and the header file should be removed from the repository. See also https://github.com/modelica/ModelicaStandardLibrary/issues/3867.
