### ISSUE TITLE
Not able to understand how to generate generic microcontroller code using the package ?

### ISSUE THREAD

**Issue by parthmpatel1110** [modelica-3rdparty/Modelica_DeviceDrivers#375]
Hi,
I am new to open-modelica. I am trying to generate Atomic c code for embedded in open-modelica. Please help me out with it.
I want to code stm32G series.

**Comment by bernhard-thiele** [comment]
Hi @parthmpatel1110,
There is very incomplete and experimental support for STM32F4 in M_DD which was added years ago and development was not continued. I don't know about the latest state in OpenModelica, but for M_DD the support is not on a level which is meant for (productive) use.

**Comment by tbeu** [comment]
@bernhard-thiele Should it be moved to Incubate to reduce expectations?
