### ISSUE TITLE
Component config of variability parameter has binding 'socketCANConfig1[<txMessage1, txMessage1>]' of higher variability continuous.

### ISSUE THREAD

**Issue by wangyuan02605** [modelica-3rdparty/Modelica_DeviceDrivers#376]
Component config of variability parameter has binding 'socketCANConfig1[<txMessage1, txMessage1>]' of higher variability continuous.

**Comment by bernhard-thiele** [comment]
Hi, welcome to MDD. Could you give more background information like

- Operating system (guess it should be Linux, but which distribution at which version)?
- Used Modelica tool and its version?
- Did the error occur at an example or was it a model you created yourself?
